# config.yml

model_type:
  rerank
# mdoel args
model:        
  model_name_or_path: "BAAI/bge-reranker-base"         #   Change to your bert model name or path 
  device: cuda   

# trainning args
traininng:
  batch_size: 2                                      
  epochs: 1000          
  learning_rate: 0.00002
  optimizer: AdamW                                                           # Currently only supports AdamW and Adam
  weight_decay: 0.0001
  clip_max_norm: 0.5
  factor: 0.3
  patience: 15         
  device: cuda

dataset_type:
  rerank
dataset:
  train_data_path: data_example/test.jsonl                                       # Replace with the training data path that you have processed yourself
  test_data_path: data_example/test.jsonl                                           # Replace with the test data path that you have processed yourself
  valid_data_path: data_example/test.jsonl                                         # Replace with the valid data path that you have processed yourself
  max_padding_length: 512                                                 # Your single data token length should not exceed 512
  train_group_size: 8


logging:
  eval_interval: 1                                          
  save_dir: "./saved_model/rerank"      